// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication4.Data;

#nullable disable

namespace WebApplication4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication4.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<int>("Manufacturer")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = 1,
                            Manufacturer = 0,
                            Model = "Malibu",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 2,
                            Color = 0,
                            Manufacturer = 0,
                            Model = "Tracker",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 3,
                            Color = 1,
                            Manufacturer = 1,
                            Model = "X6",
                            Price = 50000m
                        },
                        new
                        {
                            Id = 4,
                            Color = 2,
                            Manufacturer = 8,
                            Model = "Camry",
                            Price = 12000m
                        },
                        new
                        {
                            Id = 5,
                            Color = 3,
                            Manufacturer = 3,
                            Model = "Civic",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 6,
                            Color = 4,
                            Manufacturer = 5,
                            Model = "Focus",
                            Price = 13000m
                        },
                        new
                        {
                            Id = 7,
                            Color = 0,
                            Manufacturer = 1,
                            Model = "X5",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 8,
                            Color = 7,
                            Manufacturer = 11,
                            Model = "A4",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 9,
                            Color = 1,
                            Manufacturer = 2,
                            Model = "C-Class",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 10,
                            Color = 1,
                            Manufacturer = 6,
                            Model = "Elantra",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 11,
                            Color = 2,
                            Manufacturer = 4,
                            Model = "Optima",
                            Price = 15000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
